title: Sourabh Choraria
logo: /assets/img/logo.jpg
email: sourabh@choraria.io
description: 
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Home
    icon: <i class="fa-solid fa-house-chimney"></i>
    link: /
  - name: About
    icon: <i class="fa-solid fa-address-card"></i>
    link: /about/
  - name: Twitter
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/schoraria911
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/choraria

github: [metadata]
favicon: true